// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMupdN7ioeuMHz3ux8jVlEL5VlzCe4TUA',
    appId: '1:844411702596:web:1ae29f8a56ae1adf701b11',
    messagingSenderId: '844411702596',
    projectId: 'chess-flutter',
    authDomain: 'chess-flutter.firebaseapp.com',
    storageBucket: 'chess-flutter.appspot.com',
    measurementId: 'G-LM9T3T5JL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqq7OGJWMAc9iVvhPgRAn6DWgS_taXVkA',
    appId: '1:844411702596:android:64dd1db602781abe701b11',
    messagingSenderId: '844411702596',
    projectId: 'chess-flutter',
    storageBucket: 'chess-flutter.appspot.com',
    databaseURL: 'https://chess-flutter-default-rtdb.firebaseio.com'
  );
}
